use_frameworks!

platform :ios, '9.0'

target 'WhiteDnsHelper_Example' do
  pod 'WhiteDnsHelper', :path => '../'
  pod 'White-SDK-iOS', '~>2.1'
  pod 'Masonry'

  target 'WhiteDnsHelper_Tests' do
    inherit! :search_paths

    
  end
end
